-- =========================================================
-- 과제 주제 : 치과기공소 관리 시스템
--학번 : 202532086
--이름 : 김효정
-- =========================================================

-- =========================================================
-- 1. 초기화 (안전한 삭제)
--    기존 테이블이 있으면 삭제하고, 없으면 그냥 넘어갑니다.
--    (PL/SQL 블록을 사용하여 '테이블 없음' 에러를 방지함)
-- =========================================================
SET SERVEROUTPUT ON;
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN ('PROCESS_STEP','PAYMENT','WORK_ORDER','MATERIAL','PROSTHESIS','MEMBER','CLINIC')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
        DBMS_OUTPUT.PUT_LINE('Table ' || t.table_name || ' dropped.');
    END LOOP;
    
    FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name IN ('SEQ_CLINIC','SEQ_MEMBER','SEQ_PROS','SEQ_MAT','SEQ_ORDER','SEQ_STEP','SEQ_PAY')) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
        DBMS_OUTPUT.PUT_LINE('Sequence ' || s.sequence_name || ' dropped.');
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Init Error: ' || SQLERRM);
END;
/

-- =========================================================
-- 2. DDL: 테이블 및 시퀀스 생성 (엔터티 7개)
-- =========================================================

-- 시퀀스 생성
CREATE SEQUENCE SEQ_CLINIC START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MEMBER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PROS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MAT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ORDER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STEP START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PAY START WITH 1 INCREMENT BY 1;

-- [1] 치과 (CLINIC)
CREATE TABLE CLINIC (
    CLINIC_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    CLINIC_CODE CHAR(1) NOT NULL,
    MANAGER_NAME VARCHAR2(30),
    PHONE_NUMBER VARCHAR2(20),
    ADDRESS VARCHAR2(200),
    REG_DATE DATE DEFAULT SYSDATE
);
COMMENT ON TABLE CLINIC IS '거래처 치과 정보';

-- [2] 직원 (MEMBER)
CREATE TABLE MEMBER (
    MEMBER_ID NUMBER PRIMARY KEY,
    LOGIN_ID VARCHAR2(30) NOT NULL UNIQUE, -- [중요] 외래키 참조를 위해 UNIQUE 필수
    PASSWORD VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    ROLE VARCHAR2(10) DEFAULT 'USER',
    POSITION VARCHAR2(50),
    EMAIL VARCHAR2(50),
    PHONE_NUMBER VARCHAR2(20),
    JOIN_DATE DATE DEFAULT SYSDATE,
    WORKLOAD NUMBER DEFAULT 0,
    SKILLS VARCHAR2(200),
    AVATAR_EMOJI VARCHAR2(10)
);
COMMENT ON TABLE MEMBER IS '기공소 직원 정보';

-- [3] 교정 장치 (PROSTHESIS)
CREATE TABLE PROSTHESIS (
    TYPE_ID NUMBER PRIMARY KEY,
    TYPE_NAME VARCHAR2(50) NOT NULL,
    UNIT_PRICE NUMBER DEFAULT 0 NOT NULL
);
COMMENT ON TABLE PROSTHESIS IS '제작 가능한 교정 장치 목록';

-- [4] 교정 재료 (MATERIAL)
CREATE TABLE MATERIAL (
    MAT_ID NUMBER PRIMARY KEY,
    MAT_NAME VARCHAR2(50) NOT NULL,
    STOCK_QTY NUMBER DEFAULT 0,
    UNIT VARCHAR2(10)
);
COMMENT ON TABLE MATERIAL IS '교정용 원자재 재고';

-- [5] 의뢰서 (WORK_ORDER)
CREATE TABLE WORK_ORDER (
    ORDER_ID NUMBER PRIMARY KEY,
    ORDER_CODE VARCHAR2(30) UNIQUE,
    CLINIC_ID NUMBER NOT NULL,
    TYPE_ID NUMBER NOT NULL,
    WORKER_ID VARCHAR2(30), -- 직원 테이블의 LOGIN_ID 참조
    PATIENT_NAME VARCHAR2(30),
    RECEPTION_DATE DATE NOT NULL,
    DUE_DATE DATE NOT NULL,
    STATUS VARCHAR2(20) DEFAULT '접수',
    SHADE VARCHAR2(20),
    DIFFICULTY VARCHAR2(10) DEFAULT 'MID',
    MEMO VARCHAR2(300),
    SHIPPING_STATUS VARCHAR2(20) DEFAULT '대기',
    FINAL_PRICE NUMBER DEFAULT 0,
    IS_PAID CHAR(1) DEFAULT 'N',
    CREATED_AT DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_ORD_CLI FOREIGN KEY (CLINIC_ID) REFERENCES CLINIC(CLINIC_ID),
    CONSTRAINT FK_ORD_TYPE FOREIGN KEY (TYPE_ID) REFERENCES PROSTHESIS(TYPE_ID),
    CONSTRAINT FK_ORD_MEM FOREIGN KEY (WORKER_ID) REFERENCES MEMBER(LOGIN_ID)
);
COMMENT ON TABLE WORK_ORDER IS '기공 의뢰서 및 작업 지시서';

-- [6] 공정 단계 (PROCESS_STEP)
CREATE TABLE PROCESS_STEP (
    STEP_ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    STEP_NAME VARCHAR2(50) NOT NULL,
    WORKER_NAME VARCHAR2(30),
    FINISH_DT DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_STEP_ORD FOREIGN KEY (ORDER_ID) REFERENCES WORK_ORDER(ORDER_ID) ON DELETE CASCADE
);
COMMENT ON TABLE PROCESS_STEP IS '의뢰별 세부 공정 진행 이력';

-- [7] 결제 (PAYMENT)
CREATE TABLE PAYMENT (
    PAY_ID NUMBER PRIMARY KEY,
    CLINIC_ID NUMBER NOT NULL,
    AMOUNT NUMBER NOT NULL,
    PAY_DATE DATE DEFAULT SYSDATE,
    METHOD VARCHAR2(20),
    
    CONSTRAINT FK_PAY_CLI FOREIGN KEY (CLINIC_ID) REFERENCES CLINIC(CLINIC_ID)
);
COMMENT ON TABLE PAYMENT IS '치과별 입금내역';


-- =========================================================
-- 3. DML: 데이터 입력 (INSERT) - 30건 이상
-- =========================================================

-- 1) 치과 데이터
INSERT INTO CLINIC VALUES (SEQ_CLINIC.NEXTVAL, '바른이치과', 'A', '김실장', '02-111-2222', '서울 강남구', SYSDATE);
INSERT INTO CLINIC VALUES (SEQ_CLINIC.NEXTVAL, '가지런한치과', 'B', '이원장', '031-333-4444', '경기 분당', SYSDATE);
INSERT INTO CLINIC VALUES (SEQ_CLINIC.NEXTVAL, '스마일교정', 'C', '최원장', '051-777-8888', '부산 해운대', SYSDATE);
INSERT INTO CLINIC VALUES (SEQ_CLINIC.NEXTVAL, '연세라인', 'D', '박원장', '02-555-6666', '서울 서초', SYSDATE);
INSERT INTO CLINIC VALUES (SEQ_CLINIC.NEXTVAL, '고운미소', 'E', '정실장', '032-123-4567', '인천 부평', SYSDATE);

-- 2) 직원 데이터
INSERT INTO MEMBER VALUES (SEQ_MEMBER.NEXTVAL, 'admin', '1234', '김대표', 'ADMIN', '소장', 'ceo@lab.com', '010-1111-2222', TO_DATE('2018-01-01','YYYY-MM-DD'), 95, 'Management', '👨‍⚕️');
INSERT INTO MEMBER VALUES (SEQ_MEMBER.NEXTVAL, 'staff1', '1234', '우온달', 'USER', '기사', 'woo@lab.com', '010-3333-4444', TO_DATE('2020-05-15','YYYY-MM-DD'), 85, 'Wire Bending', '🔧');
INSERT INTO MEMBER VALUES (SEQ_MEMBER.NEXTVAL, 'staff2', '1234', '성춘향', 'USER', '실장', 'sung@lab.com', '010-5555-5555', TO_DATE('2021-03-10','YYYY-MM-DD'), 75, 'Resin Art', '🎨');
INSERT INTO MEMBER VALUES (SEQ_MEMBER.NEXTVAL, 'staff3', '1234', '홍길동', 'USER', '기사', 'hong@lab.com', '010-7777-7777', TO_DATE('2022-07-20','YYYY-MM-DD'), 65, 'CAD/CAM', '💻');

-- 3) 교정 장치 데이터
INSERT INTO PROSTHESIS VALUES (SEQ_PROS.NEXTVAL, 'C-Retainer', 80000);
INSERT INTO PROSTHESIS VALUES (SEQ_PROS.NEXTVAL, 'Hawley Retainer', 90000);
INSERT INTO PROSTHESIS VALUES (SEQ_PROS.NEXTVAL, 'Fixed Retainer', 40000);
INSERT INTO PROSTHESIS VALUES (SEQ_PROS.NEXTVAL, 'R.P.E', 150000);
INSERT INTO PROSTHESIS VALUES (SEQ_PROS.NEXTVAL, 'Twin Block', 300000);
INSERT INTO PROSTHESIS VALUES (SEQ_PROS.NEXTVAL, 'Clear Aligner', 60000);
INSERT INTO PROSTHESIS VALUES (SEQ_PROS.NEXTVAL, 'Bleaching Tray', 50000);
INSERT INTO PROSTHESIS VALUES (SEQ_PROS.NEXTVAL, 'Lingual Arch', 60000);

-- 4) 재료 데이터
INSERT INTO MATERIAL VALUES (SEQ_MAT.NEXTVAL, 'Ortho Wire 0.7mm', 10, 'roll');
INSERT INTO MATERIAL VALUES (SEQ_MAT.NEXTVAL, 'Ortho Wire 0.8mm', 8, 'roll');
INSERT INTO MATERIAL VALUES (SEQ_MAT.NEXTVAL, 'Ortho Resin (Pink)', 20, 'btl');
INSERT INTO MATERIAL VALUES (SEQ_MAT.NEXTVAL, 'Ortho Resin (Clear)', 15, 'btl');
INSERT INTO MATERIAL VALUES (SEQ_MAT.NEXTVAL, 'Expansion Screw', 50, 'ea');

-- 5) 의뢰서 데이터
INSERT INTO WORK_ORDER VALUES (SEQ_ORDER.NEXTVAL, '20251201-A-01', 1, 1, 'staff1', '손흥민', TO_DATE('2025-12-01','YYYY-MM-DD'), TO_DATE('2025-12-05','YYYY-MM-DD'), '배송완료', '', 'LOW', '', '완료', 80000, 'Y', SYSDATE);
INSERT INTO WORK_ORDER VALUES (SEQ_ORDER.NEXTVAL, '20251201-B-01', 2, 2, 'staff2', '김연아', TO_DATE('2025-12-01','YYYY-MM-DD'), TO_DATE('2025-12-06','YYYY-MM-DD'), '배송완료', 'A2', 'MID', '', '완료', 90000, 'N', SYSDATE);
INSERT INTO WORK_ORDER VALUES (SEQ_ORDER.NEXTVAL, '20251202-C-01', 3, 4, 'staff1', '유재석', TO_DATE('2025-12-02','YYYY-MM-DD'), TO_DATE('2025-12-08','YYYY-MM-DD'), '작업완료', '', 'HIGH', '스크류 추가', '대기', 150000, 'N', SYSDATE);
INSERT INTO WORK_ORDER VALUES (SEQ_ORDER.NEXTVAL, '20251202-A-02', 1, 5, 'staff3', '아이유', TO_DATE('2025-12-02','YYYY-MM-DD'), TO_DATE('2025-12-09','YYYY-MM-DD'), '제작중', 'Blue', 'HIGH', '', '대기', 300000, 'N', SYSDATE);
INSERT INTO WORK_ORDER VALUES (SEQ_ORDER.NEXTVAL, '20251203-D-01', 4, 1, 'staff1', '강호동', TO_DATE('2025-12-03','YYYY-MM-DD'), TO_DATE('2025-12-07','YYYY-MM-DD'), '접수', '', 'LOW', '', '대기', 80000, 'N', SYSDATE);
INSERT INTO WORK_ORDER VALUES (SEQ_ORDER.NEXTVAL, '20251203-E-01', 5, 6, 'staff3', '차은우', TO_DATE('2025-12-03','YYYY-MM-DD'), TO_DATE('2025-12-08','YYYY-MM-DD'), '접수', '', 'LOW', '', '대기', 60000, 'N', SYSDATE);
INSERT INTO WORK_ORDER VALUES (SEQ_ORDER.NEXTVAL, '20251204-B-02', 2, 8, '장원영', 'staff1', '2025-12-04','YYYY-MM-DD', TO_DATE('2025-12-10','YYYY-MM-DD'), '제작중', '', 'MID', '', '대기', 60000, 'N', SYSDATE);
INSERT INTO WORK_ORDER VALUES (SEQ_ORDER.NEXTVAL, '20251205-A-03', 1, 2, '박서준', 'staff2', '2025-12-05','YYYY-MM-DD', TO_DATE('2025-12-11','YYYY-MM-DD'), '접수', 'Pink', 'MID', '', '대기', 90000, 'N', SYSDATE);
INSERT INTO WORK_ORDER VALUES (SEQ_ORDER.NEXTVAL, '20251206-C-02', 3, 5, '제니', 'staff3', '2025-12-06','YYYY-MM-DD', TO_DATE('2025-12-13','YYYY-MM-DD'), '접수', '', 'HIGH', '', '대기', 300000, 'N', SYSDATE);
INSERT INTO WORK_ORDER VALUES (SEQ_ORDER.NEXTVAL, '20251207-D-02', 4, 3, '뷔', 'staff1', '2025-12-07','YYYY-MM-DD', TO_DATE('2025-12-10','YYYY-MM-DD'), '접수', '', 'LOW', '급함', '대기', 40000, 'N', SYSDATE);

-- 6) 공정 단계 입력
INSERT INTO PROCESS_STEP VALUES (SEQ_STEP.NEXTVAL, 1, 'Wire Bending', '우온달', SYSDATE);
INSERT INTO PROCESS_STEP VALUES (SEQ_STEP.NEXTVAL, 1, 'Resin Pouring', '성춘향', SYSDATE);
INSERT INTO PROCESS_STEP VALUES (SEQ_STEP.NEXTVAL, 1, 'Polishing', '우온달', SYSDATE);
INSERT INTO PROCESS_STEP VALUES (SEQ_STEP.NEXTVAL, 2, 'Wire Bending', '성춘향', SYSDATE);
INSERT INTO PROCESS_STEP VALUES (SEQ_STEP.NEXTVAL, 2, 'Finishing', '성춘향', SYSDATE);
INSERT INTO PROCESS_STEP VALUES (SEQ_STEP.NEXTVAL, 4, 'Design', '홍길동', SYSDATE);
INSERT INTO PROCESS_STEP VALUES (SEQ_STEP.NEXTVAL, 4, '3D Printing', '홍길동', SYSDATE);

-- 7) 결제 데이터 입력
INSERT INTO PAYMENT VALUES (SEQ_PAY.NEXTVAL, 1, 80000, SYSDATE, '계좌이체');
INSERT INTO PAYMENT VALUES (SEQ_PAY.NEXTVAL, 2, 50000, SYSDATE, '카드');

-- =========================================================
-- 문제

--1. 한 개의 테이블 선택하기 
-- 의뢰서 테이블에서 2025/12/02 접수된 의뢰의 의뢰번호, 환자명, 담당자 id
SELECT ORDER_CODE, PATIENT_NAME, WORKER_ID
FROM WORK_ORDER 
WHERE RECEPTION_DATE = TO_DATE('2025-12-02', 'YYYY-MM-DD');

--2. 두 개의 테이블 JOIN하기
--의뢰서와 치과테이블 연결하여, 의뢰된 환자명, 치과명, 담당자 전화번호 나열
SELECT W.PATIENT_NAME, C.NAME AS CLINIC_NAME, C.PHONE_NUMBER
FROM WORK_ORDER W
JOIN CLINIC C ON W.CLINIC_ID = C.CLINIC_ID;

--3.비교 연산자
--의뢰서 테이블에서 청구된 금액이 150000원 이상인 건의 의뢰번호, 환자명, 금액을 구하기
SELECT ORDER_CODE, PATIENT_NAME, FINAL_PRICE
FROM WORK_ORDER
WHERE FINAL_PRICE >= 150000;

--4.AND 연산자
--의뢰서 테이블에서 상태가 배송완료이면서 아직 입금되지 않은 건을 조회
SELECT * FROM WORK_ORDER
WHERE STATUS = '배송완료' AND  IS_PAID ='N';

--5.OR 연산자
--직원 테이블에서 직급이 소장이거나 실장인 직원의 이름과 직급 구하기
SELECT NAME, POSITION
FROM MEMBER
WHERE POSITION = '소장' OR POSITION = '실장';

--6.NOT연산자
--치과 테이블에서 주소가 '서울'이 아닌 치과의 이름과 주소 구하기
SELECT NAME, ADDRESS
FROM CLINIC 
WHERE ADDRESS NOT LIKE '%서울%';

--7.LIKE 연산자(부분일치)
--교정장치 테이블에서 이름에 'retainer'가 포함된 장이 이름과 단가 구하기
SELECT TYPE_NAME, UNIT_PRICE 
FROM PROSTHESIS 
WHERE TYPE_NAME LIKE '%Retainer%';

--8.BETWEEN 연산자
--의뢰서 테이블에서 청구금액이 50000~100000원 사이인 건 조회
SELECT PATIENT_NAME, FINAL_PRICE
FROM WORK_ORDER
WHERE FINAL_PRICE BETWEEN 50000 AND 100000;

--9.IN 연산자
--치과테이블에서 주소가 '서울 강남구' 혹은 '경기 분당'인 치과 조회
SELECT NAME, ADDRESS
FROM CLINIC
WHERE ADDRESS IN ('서울 강남구', '경기 분당');

--10.ALL(서브쿼리)
--모든 'wire' 관련 재료의 재고량보다 재고가 많은 재료를 조회
SELECT * FROM MATERIAL
WHERE STOCK_QTY > ALL (SELECT STOCK_QTY FROM MATERIAL WHERE MAT_NAME LIKE '%Wire%');

--11.ANT(서브쿼리)
--twin block을 의뢰한 적이 있는  치과의 이름을 조회하시오
SELECT NAME
FROM CLINIC
WHERE CLINIC_ID = ANY(
    SELECT CLINIC_ID FROM WORK_ORDER
    WHERE TYPE_ID = (SELECT TYPE_ID FROM PROSTHESIS WHERE TYPE_NAME = 'Twin Block')
);

--12.EXISTS
--미수금이 있는 치과의 이름과 연락처 구하기
SELECT NAME, PHONE_NUMBER
FROM CLINIC C
WHERE EXISTS ( SELECT 1 FROM WORK_ORDER W WHERE W.CLINIC_ID  = C.CLINIC_ID AND W.IS_PAID = 'N');

--13.NOT EXISTS
-- 아직 한 번도 의뢰를 하지 않은 치과를 조회하시오
SELECT NAME 
FROM CLINIC C
WHERE NOT EXISTS (SELECT 1 FROM WORK_ORDER W WHERE W.CLINIC_ID  = C. CLINIC_ID);

--14.계산한 값의 검색
--의뢰서 테이블에서 부가세 (10%)를 포함한 예상 청구금액을 계산하여 표시
SELECT PATIENT_NAME, FINAL_PRICE, FINAL_PRICE *1.1 AS "VAT포함금액"
FROM WORK_ORDER;

--15.COUNT 
-- 현재 등록된 총 의뢰 건수
SELECT COUNT (*) AS "총 의뢰 건수" FROM WORK_ORDER;

--16.SUM
--이번달 총 예상 매출액
SELECT SUM(FINAL_PRICE) AS "총 매출액" FROM WORK_ORDER;

--17.AVG
--등록된 교정장치 평균 단가
SELECT AVG(UNIT_PRICE) AS "평균단가" FROM PROSTHESIS;

--18.MAX
--가장 비싼 의뢰 건의 금액과 환자명
SELECT PATIENT_NAME, FINAL_PRICE
FROM WORK_ORDER
WHERE FINAL_PRICE =(SELECT MAX(FINAL_PRICE) FROM WORK_ORDER);

--19.MIN
--가장 적게 남은 재료의 이름과 수량을 구하시오
SELECT MAT_NAME, STOCK_QTY
FROM MATERIAL
WHERE STOCK_QTY = (SELECT MIN(STOCK_QTY) FROM MATERIAL);

--20.ORDER BY
--의뢰서 테이블을 납기일이 빠른 순서대로 정렬하여 조회
SELECT PATIENT_NAME, DUE_DATE, STATUS
FROM WORK_ORDER
ORDER BY DUE_DATE ASC;

--21.GROUP BY
--치과별로 총 의뢰 건수
SELECT CLINIC_ID, COUNT(*) AS "주문건수"
FROM WORK_ORDER
GROUP BY CLINIC_ID;

--22.DISTINCT
--의뢰가 들어온 적 있는 치과들의 id를 중복 없이 조회
SELECT DISTINCT CLINIC_ID FROM WORK_ORDER;

--23.AS
--직원 테이블에서 이름, 전화번호, 담당업무 한글 별칭으로 조회
SELECT NAME AS "이름",PHONE_NUMBER AS "연락처", SKILLS AS "담당업무"
FROM MEMBER;

--24.HAVING
--총 주문 금액합계가 300000원 이상인 치과 ID와 총액
SELECT CLINIC_ID, SUM(FINAL_PRICE)
FROM WORK_ORDER
GROUP BY CLINIC_ID
HAVING SUM(FINAL_PRICE) >= 300000;

--25.HVING
--2회 이상 의뢰한 치과의 id를 구하시오
SELECT CLINIC_ID
FROM WORK_ORDER
GROUP BY CLINIC_ID
HAVING COUNT(*) >= 2;

--26.UPDATE
--바른이치과의 담당자 이름을 박실장으로 주소를 서울 서초구로 수정하시오
UPDATE CLINIC
SET MANAGER_NAME ='박실장', ADDRESS = '서울 서초구'
WHERE NAME = '바른이치과';

--27.UPDATE
--'서울'에 위치한 치과에서 주문한 의뢰의 상태를 모두 배송완료로 변경
UPDATE WORK_ORDER
SET STATUS = '배송완료'
WHERE CLINIC_ID IN (SELECT CLINIC_ID FROM CLINIC WHERE ADDRESS LIKE '%서울%');

--28.UPDATE
--재료 ortho wire 0.7mm의 재고를 5개 차감
UPDATE MATERIAL
SET STOCK_QTY = STOCK_QTY -5
WHERE MAT_NAME = 'Ortho Wire - 0.7mm';

--29.INSERT
--새로운 교정 장치 invisible retainer(단가 120000원)을 추가 
INSERT INTO PROSTHESIS(TYPE_ID, TYPE_NAME, UNIT_PRICE)
VALUES (SEQ_PROS.NEXTVAL, 'Invisible Retainer', 120000);

--30.DELECT
--방금 추가한 invisible retainer 삭제
DELETE FROM PROSTHESIS
WHERE TYPE_NAME = 'Invisible Retainer';

COMMIT;